name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1

      - name: Build tests
        run: |
          cargo test --all-features --no-run

      - name: Run unit tests
        run: |
          cargo test --all-features
          cargo test --examples --all-features
        env:
          RUST_BACKTRACE: 1